<?php

namespace BJ\ReservationBundle\Repository;

/**
 * typeTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
