# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    bj_reservation_pricemanager:
        class: BJ\ReservationBundle\Services\PriceManager

    app.more_than_thousand_tickets_validator:
        class: BJ\ReservationBundle\Validator\Constraints\MoreThanThousandTicketsValidator
        arguments:
            - ["@doctrine.orm.entity_manager"]
            - ["@request_stack"]
        tags:
            - { name: validator.constraint_validator }