# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    bj_reservation_pricemanager:
        class: BJ\ReservationBundle\Services\PriceManager
