# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    bj_reservation_pricemanager:
        class: BJ\ReservationBundle\Services\PriceManager

    bj_reservation_emailmanager:
        class: BJ\ReservationBundle\Services\EmailManager
        arguments: ["@mailer", "@templating"]

    bj.reservation_codereservationmanager:
        class: BJ\ReservationBundle\Services\CodeReservationManager

    app.more_than_thousand_tickets:
        class: BJ\ReservationBundle\Validator\Constraints\MoreThanThousandTicketsValidator
        # In the validator, we need the entity manager, but we also need
        # to access the request, a.k.a the form data
        arguments: ['@doctrine.orm.entity_manager', '@request_stack']
        tags:
            - { name: validator.constraint_validator, alias: app_thousand }